-- Rocycle Project PostgreSQL schema
-- Tables: waste_type -> processing_log -> robot_event
-- This file is idempotent: it can also upgrade the original three-table schema.

BEGIN;

CREATE TABLE IF NOT EXISTS waste_type (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_name      VARCHAR(50) NOT NULL UNIQUE,
    material        VARCHAR(50),
    graspable       BOOLEAN NOT NULL DEFAULT true,
    label_check     BOOLEAN NOT NULL DEFAULT false,
    content_check   BOOLEAN NOT NULL DEFAULT false,
    destination     VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS processing_log (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id         VARCHAR(120),
    waste_type_id       INTEGER REFERENCES waste_type(id),
    confidence          REAL,
    action              VARCHAR(50),
    destination         VARCHAR(50),
    result              VARCHAR(30),
    static_force        REAL,
    torque_change       REAL,
    created_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    final_waste_type_id INTEGER REFERENCES waste_type(id),
    final_destination   VARCHAR(50),
    status              VARCHAR(30) NOT NULL DEFAULT 'processing',
    review_reason       VARCHAR(50),
    weight              REAL,
    completed_at        TIMESTAMP,
    reviewed_at         TIMESTAMP,
    reviewed_by         VARCHAR(100),
    updated_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Upgrade an existing installation created from the earlier schema.
ALTER TABLE processing_log
    ADD COLUMN IF NOT EXISTS final_waste_type_id INTEGER REFERENCES waste_type(id),
    ADD COLUMN IF NOT EXISTS final_destination VARCHAR(50),
    ADD COLUMN IF NOT EXISTS status VARCHAR(30) NOT NULL DEFAULT 'processing',
    ADD COLUMN IF NOT EXISTS review_reason VARCHAR(50),
    ADD COLUMN IF NOT EXISTS weight REAL,
    ADD COLUMN IF NOT EXISTS completed_at TIMESTAMP,
    ADD COLUMN IF NOT EXISTS reviewed_at TIMESTAMP,
    ADD COLUMN IF NOT EXISTS reviewed_by VARCHAR(100),
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE processing_log
    ADD COLUMN IF NOT EXISTS external_id VARCHAR(120);

CREATE TABLE IF NOT EXISTS robot_event (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    processing_log_id   INTEGER REFERENCES processing_log(id),
    event_type          VARCHAR(50) NOT NULL,
    detail              TEXT,
    created_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_processing_log_waste_type_id
    ON processing_log(waste_type_id);
CREATE INDEX IF NOT EXISTS idx_processing_log_created_at
    ON processing_log(created_at);
CREATE INDEX IF NOT EXISTS idx_processing_log_result
    ON processing_log(result);
CREATE INDEX IF NOT EXISTS idx_processing_log_status
    ON processing_log(status);
CREATE INDEX IF NOT EXISTS idx_processing_log_completed_at
    ON processing_log(completed_at);

-- Keep the legacy values while allowing the current UI/robot bridge vocabulary.
ALTER TABLE processing_log
    DROP CONSTRAINT IF EXISTS chk_processing_result;
ALTER TABLE processing_log
    ADD CONSTRAINT chk_processing_result CHECK (
        result IS NULL OR result IN (
            'completed', 'success', 'review', 'handed_to_human',
            'assist_timeout', 'passed_undetected', 'passed_grasp_failed'
        )
    );

ALTER TABLE processing_log
    DROP CONSTRAINT IF EXISTS chk_review_reason;
ALTER TABLE processing_log
    ADD CONSTRAINT chk_review_reason CHECK (
        review_reason IS NULL OR review_reason IN (
            'has_content', 'unknown_content', 'ambiguous', 'assist_timeout',
            'weight_exceeded', 'weight_measurement_unreliable',
            'low_confidence', 'handoff_timeout',
            'manual_review', 'manual_review_required'
        )
    );
CREATE INDEX IF NOT EXISTS idx_processing_log_reviewed_at
    ON processing_log(reviewed_at);
CREATE UNIQUE INDEX IF NOT EXISTS idx_processing_log_external_id
    ON processing_log(external_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_waste_type_class_name
    ON waste_type(class_name);
CREATE INDEX IF NOT EXISTS idx_robot_event_processing_log_id
    ON robot_event(processing_log_id);
CREATE INDEX IF NOT EXISTS idx_robot_event_created_at
    ON robot_event(created_at);

-- Upgrade the two legacy PET class names without breaking existing foreign keys.
DO $$
DECLARE
    old_id INTEGER;
    new_id INTEGER;
BEGIN
    SELECT id INTO old_id FROM waste_type WHERE class_name = 'pet_bottle_labeled';
    SELECT id INTO new_id FROM waste_type WHERE class_name = 'pet_labeled';
    IF old_id IS NOT NULL AND new_id IS NULL THEN
        UPDATE waste_type SET class_name = 'pet_labeled' WHERE id = old_id;
    ELSIF old_id IS NOT NULL AND new_id IS NOT NULL THEN
        UPDATE processing_log SET waste_type_id = new_id WHERE waste_type_id = old_id;
        UPDATE processing_log SET final_waste_type_id = new_id WHERE final_waste_type_id = old_id;
        DELETE FROM waste_type WHERE id = old_id;
    END IF;

    old_id := NULL;
    new_id := NULL;
    SELECT id INTO old_id FROM waste_type WHERE class_name = 'pet_bottle_unlabeled';
    SELECT id INTO new_id FROM waste_type WHERE class_name = 'plastic';
    IF old_id IS NOT NULL AND new_id IS NULL THEN
        UPDATE waste_type SET class_name = 'plastic' WHERE id = old_id;
    ELSIF old_id IS NOT NULL AND new_id IS NOT NULL THEN
        UPDATE processing_log SET waste_type_id = new_id WHERE waste_type_id = old_id;
        UPDATE processing_log SET final_waste_type_id = new_id WHERE final_waste_type_id = old_id;
        DELETE FROM waste_type WHERE id = old_id;
    END IF;
END $$;

-- Class/destination master data used by both the robot and the review UI.
INSERT INTO waste_type
    (class_name, material, graspable, label_check, content_check, destination)
VALUES
    ('battery',     'battery', true,  false, false, 'battery_bin'),
    ('can',         'metal',   true,  false, true,  'can_bin'),
    ('paper',       'paper',   true,  false, false, 'paper_bin'),
    ('pet_labeled', 'plastic', true,  true,  true,  'human_handoff'),
    ('plastic',     'plastic', true,  false, false, 'plastic_bin'),
    -- The robot first places this class in review_bin. The API records
    -- plastic_bin as its logical destination after an operator confirms it.
    ('plastic_bag', 'plastic', true,  false, false, 'review_bin')
ON CONFLICT (class_name) DO UPDATE SET
    material = EXCLUDED.material,
    graspable = EXCLUDED.graspable,
    label_check = EXCLUDED.label_check,
    content_check = EXCLUDED.content_check,
    destination = EXCLUDED.destination;

-- Preserve useful legacy rows when this migration is applied to a populated DB.
-- `weight` stores kilograms, matching the robot weight service output.
UPDATE processing_log
SET status = 'review_pending',
    updated_at = CURRENT_TIMESTAMP
WHERE status = 'processing'
  AND (result IN ('review', 'assist_timeout') OR destination = 'review_bin');

UPDATE processing_log
SET status = 'completed',
    completed_at = COALESCE(completed_at, created_at),
    final_waste_type_id = COALESCE(final_waste_type_id, waste_type_id),
    final_destination = COALESCE(final_destination, destination),
    updated_at = CURRENT_TIMESTAMP
WHERE status = 'processing'
  AND result IN ('success', 'completed', 'ok', 'handed_to_human');

UPDATE processing_log
SET status = 'failed',
    updated_at = CURRENT_TIMESTAMP
WHERE status = 'processing'
  AND result IN ('passed_timeout', 'passed_undetected', 'passed_grasp_failed');

COMMIT;
