-- Rocycle Project PostgreSQL schema
-- Tables: waste_type -> processing_log -> robot_event

BEGIN;

CREATE TABLE IF NOT EXISTS waste_type (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_name      VARCHAR(50) NOT NULL UNIQUE,
    material        VARCHAR(50),
    graspable       BOOLEAN,
    label_check     BOOLEAN,
    content_check   BOOLEAN,
    destination     VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS processing_log (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    waste_type_id       INTEGER REFERENCES waste_type(id),
    confidence          REAL,
    action              VARCHAR(50),
    destination         VARCHAR(50),
    result              VARCHAR(30),
    content_state       VARCHAR(30),
    static_force        REAL,
    torque_change       REAL,
    interaction_type    VARCHAR(50),
    user_response       VARCHAR(50),
    created_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS robot_event (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    processing_log_id   INTEGER REFERENCES processing_log(id),
    event_type          VARCHAR(50),
    detail              TEXT,
    created_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_processing_log_waste_type_id
    ON processing_log(waste_type_id);
CREATE INDEX IF NOT EXISTS idx_processing_log_created_at
    ON processing_log(created_at);
CREATE INDEX IF NOT EXISTS idx_processing_log_result
    ON processing_log(result);
CREATE INDEX IF NOT EXISTS idx_robot_event_processing_log_id
    ON robot_event(processing_log_id);
CREATE INDEX IF NOT EXISTS idx_robot_event_created_at
    ON robot_event(created_at);

COMMIT;
